// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quantex.API.Data;

#nullable disable

namespace Quantex.API.Migrations
{
    [DbContext(typeof(QuantextContext))]
    [Migration("20251110143148_AddGroups_Profiles_Schemes_Tables")]
    partial class AddGroups_Profiles_Schemes_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("main")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quantex.API.Models.ExpenseGroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionJSON")
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ExpenseGroups", "main");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionJSON")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchemeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchemeId");

                    b.ToTable("ExpenseProfiles", "main");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseSchemeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExpenseSchemes", "main");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseUnitModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationJSON")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("ConditionJSON")
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("ExpenseUnits", "main");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseGroupModel", b =>
                {
                    b.HasOne("Quantex.API.Models.ExpenseProfileModel", "Profile")
                        .WithMany("Groups")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseProfileModel", b =>
                {
                    b.HasOne("Quantex.API.Models.ExpenseSchemeModel", "Scheme")
                        .WithMany("Profiles")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scheme");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseUnitModel", b =>
                {
                    b.HasOne("Quantex.API.Models.ExpenseGroupModel", "Group")
                        .WithMany("Units")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseGroupModel", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseProfileModel", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Quantex.API.Models.ExpenseSchemeModel", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
